### ISSUE TITLE
ARM Linux support

### ISSUE THREAD

**Issue by gohai** [samplecount/shake-language-c#31]
Trying to build Methcla on an ARMv7 running Linux:

    ./shake .update
    Unknown host architecture armv7l
    CallStack (from HasCallStack):
    error, called at src/Development/Shake/Language/C/Host/Linux.hs:33:14 in shake-language-c-0.10.0-3OxHz2LdZSyIlVaBYgvPMo:Development.Shake.Language.C.Host.Linux

**Comment by kaoskorobase** [comment]
Hi, could you please try the above commit in the branch `31-arm-linux-support`? Let's see where it takes us :)

**Comment by gohai** [comment]
Could you give me a hint how to test this? I've managed to check out shake-language-c, and build a similar change, but I couldn't figure out how to inject these (library?) files into the Methcla's build process (when I do `./shake .update`).

**Comment by kaoskorobase** [comment]
In Methcla's `stack.yaml` add the following:

```
packages:
- '.'
- '../path/to/shake-language-c'
```

Methcla's build system should then pick up the local copy of `shake-language-c`.

**Comment by gohai** [comment]
It gets a bit further, but ultimately fails like so:

    $ ./shake .update
    methcla-shakefile-0.2: unregistering
    shake-language-c-0.10.0: configure (lib)
    shake-language-c-0.10.0: build (lib)
    shake-language-c-0.10.0: copy/register
    methcla-shakefile-0.2: build (lib + exe)
    methcla-shakefile-0.2: copy/register
    Completed 2 action(s).
    Log files have been written to: /home/pi/Downloads/methcla/.stack-work/logs/
    methcla-shakefile: setNumCapabilities: not supported on this platform
    Error when running Shake build system:
    * .update
    Error, file does not exist and no rule available:
      .update
    CallStack (from HasCallStack):
      error, called at src/Development/Shake/Rules/File.hs:103:58 in shake-0.15.10-Ei8TLlAW8tZCZ770HaImXV:Development.Shake.Rules.File

**Comment by gohai** [comment]
The only mention of `numCapabilities` I find in Methcla and Shake is this in Shake's `Core.hs`:

    run :: ShakeOptions -> Rules () -> IO ()
    run opts@ShakeOptions{..} rs = (if shakeLineBuffering then lineBuffering else id) $ do
    (...)
    withCleanup $ \cleanup -> do
      (...)
       withNumCapabilities shakeThreads $ do

**Comment by gohai** [comment]
Oddly, it seems that I was able to compile Methcla after this error after all. I ran `./shake -j1 desktop`, which seem to have succeeded. So I guess that change should go in @kaoskorobase - definitely better than before.

**Comment by kaoskorobase** [comment]
The message about `setNumCapabilities` is only a warning. `.update` is not a valid target in the build system, I guess I should `.update` the README ;)

**Comment by gohai** [comment]
Thanks!

**Comment by kaoskorobase** [comment]
There's a new [version 0.10.1 on Hackage](https://hackage.haskell.org/package/shake-language-c-0.10.1); I'll update the Methcla build system as soon as it's in Stackage, too. Thanks for reporting!
